### PR TITLE
svgomg 0.6

### PR DESCRIPTION
**Pull request by redmunds**
Update to svgomg 0.6

cc @chrisbank

### CODE REVIEW

**Comment by jaredadobe** [comment]
It would appear that the logging has been dropped some where between the internal repo and our repo.

To enable bug reporting for svgomg we need to drop it back in, this seems a good a place as any
inside render.js 

```
  return svgOMG.getGeneratorSVG(this._generator, params).then(
```
Needs to become 
```
  return svgOMG.getGeneratorSVG(this._generator, params, this._logger).then(
```

**Comment by redmunds** [comment]
> It would appear that the logging has been dropped some where between the internal repo and our repo.

I think the problem is that all development is done in internal repo and then those changes are force pushed onto this repo. So making the change here will cause it to eventually get blown away again. Does that sound right @dirkschulze ?

With all of that said, I will make the change in this repo anyway (knowing that it's temporary) for the testing that needs to get done very soon.

**Comment by chrisbank** [comment]
checks pass, good looks good, merging

**Comment by dirkschulze** [comment]
@redmunds I do not know how generator-assets is managed. So I don't know if there is any trouble in the future where logging would be thrown away. I hope we make sure that this isn't the case though :).

**Comment by redmunds** [comment]
@dirkschulze 

> I do not know how generator-assets is managed...

Sorry, wrong repo :)

@jaredadobe It looks like your change to the private repo has not yet been pulled to this repo.

**Pull request merged**
